name: hello

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run custom action
      uses: taku-o/github-docker-actions-demo@master
      with:
        who-to-greet: 'hello hello'

